# Generated by Django 4.1 on 2022-09-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.FileField(upload_to='products'),
        ),
    ]
