# Generated by Django 4.1 on 2022-09-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
