# Generated by Django 4.1 on 2022-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_items_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
