# Generated by Django 4.1 on 2022-10-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_pageview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
